name: Bug Report
description: File a bug
body:
- type: input
  id: python_version
  attributes:
    label: Python Version
    description: Which version of Python were you using?
    placeholder: 3.12.0
  validations:
    required: false
- type: input
  id: django_version
  attributes:
    label: Django Version
    description: Which version of Django were you using?
    placeholder: 5.0.0
  validations:
    required: false
- type: input
  id: package_version
  attributes:
    label: Package Version
    description: Which version of this package were you using? If not the latest version, please check this issue has not since been resolved.
    placeholder: 0.10.0
  validations:
    required: false
- type: textarea
  id: description
  attributes:
    label: Description
    description: Please describe the bug
  validations:
    required: true
