blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/matagus/django-pagination-py3/discussions/new?category=q-a&title=[Question]
    about: Ask questions and discuss with other community members
